#+TITLE: collatz_func.c and collatz_main.c tests 
#+TESTY: PREFIX=collatz

* collatz_next(1)
Runs collatz_next() on argument 1 which should return 0 as starting
point 1 is 'converged' for the Collatz sequence.

#+TESTY: program='./test_collatz next 1'
#+BEGIN_SRC sh
running collatz_next(1)
returned: 0
#+END_SRC

* collatz_next(0)
Runs collatz_next() on argument 0, should return -1

#+TESTY: program='./test_collatz next 0'
#+BEGIN_SRC sh
running collatz_next(0)
returned: -1
#+END_SRC

* collatz_next(-5)
Runs collatz_next() on argument -5, should return -1

#+TESTY: program='./test_collatz next -5'
#+BEGIN_SRC sh
running collatz_next(-5)
returned: -1
#+END_SRC

* collatz_next(5)
Runs collatz_next() on argument 5

#+TESTY: program='./test_collatz next 5'
#+BEGIN_SRC sh
running collatz_next(5)
returned: 16
#+END_SRC

* collatz_next(16)
Runs collatz_next(16) 

#+TESTY: program='./test_collatz next 16'
#+BEGIN_SRC sh
running collatz_next(16)
returned: 8
#+END_SRC

* collatz_next(20)
Runs collatz_next(20) 

#+TESTY: program='./test_collatz next 20'
#+BEGIN_SRC sh
running collatz_next(20)
returned: 10
#+END_SRC

* collatz_next(15)
Runs collatz_next(15) 

#+TESTY: program='./test_collatz next 15'
#+BEGIN_SRC sh
running collatz_next(15)
returned: 46
#+END_SRC

* collatz_steps() from -7
Runs collatz_next(-7,0), should return 0 with no output

#+TESTY: program='./test_collatz steps -7 0'
#+BEGIN_SRC sh
running collatz_steps(-7, 0)
returned: 0
#+END_SRC

Runs collatz_next(-7,1), should return 0 with one line of output.

#+TESTY: program='./test_collatz steps -7 1'
#+BEGIN_SRC sh
running collatz_steps(-7, 1)
Step 0: -7
returned: 0
#+END_SRC

* collatz_steps() from 1
Runs collatz_next(1,0), should return 0 with no output

#+TESTY: program='./test_collatz steps 1 0'
#+BEGIN_SRC sh
running collatz_steps(1, 0)
returned: 0
#+END_SRC

Runs collatz_next(1,1), should return 0 with one line of output.

#+TESTY: program='./test_collatz steps 1 1'
#+BEGIN_SRC sh
running collatz_steps(1, 1)
Step 0: 1
returned: 0
#+END_SRC

* collatz_steps() from 5
Runs collatz_next(5,0), should return steps with no output

#+TESTY: program='./test_collatz steps 5 0'
#+BEGIN_SRC sh
running collatz_steps(5, 0)
returned: 5
#+END_SRC

Runs collatz_next(5,1), should return steps with some lines of output.

#+TESTY: program='./test_collatz steps 5 1'
#+BEGIN_SRC sh
running collatz_steps(5, 1)
Step 0: 5
Step 1: 16
Step 2: 8
Step 3: 4
Step 4: 2
Step 5: 1
returned: 5
#+END_SRC

* collatz_steps() from 30
Runs collatz_next(30,0), should return steps with no output

#+TESTY: program='./test_collatz steps 30 0'
#+BEGIN_SRC sh
running collatz_steps(30, 0)
returned: 18
#+END_SRC

Runs collatz_next(30, 1), should return steps with some lines of
output. 

#+TESTY: program='./test_collatz steps 30 1'
#+BEGIN_SRC sh
running collatz_steps(30, 1)
Step 0: 30
Step 1: 15
Step 2: 46
Step 3: 23
Step 4: 70
Step 5: 35
Step 6: 106
Step 7: 53
Step 8: 160
Step 9: 80
Step 10: 40
Step 11: 20
Step 12: 10
Step 13: 5
Step 14: 16
Step 15: 8
Step 16: 4
Step 17: 2
Step 18: 1
returned: 18
#+END_SRC

* collatz_steps() from 14
Runs collatz_next(14,0), should return steps with no output

#+TESTY: program='./test_collatz steps 14 0'
#+BEGIN_SRC sh
running collatz_steps(14, 0)
returned: 17
#+END_SRC

Runs collatz_next(14, 5), should return steps with some lines of
output. Note that the '5' is non-zero which should trigger output.

#+TESTY: program='./test_collatz steps 14 5'
#+BEGIN_SRC sh
running collatz_steps(14, 5)
Step 0: 14
Step 1: 7
Step 2: 22
Step 3: 11
Step 4: 34
Step 5: 17
Step 6: 52
Step 7: 26
Step 8: 13
Step 9: 40
Step 10: 20
Step 11: 10
Step 12: 5
Step 13: 16
Step 14: 8
Step 15: 4
Step 16: 2
Step 17: 1
returned: 17
#+END_SRC
* collatz_main session from 5
Run collatz_main from 5, 0 for verbose input should lead to few lines
of output.
#+TESTY: program='./collatz_main -echo'
#+BEGIN_SRC sh
Enter the starting integer:
>> 5
The next value in the Collatz sequence is 16
Show output of steps (0:NO, any other int: yes):
>> 0
The starting value 5 converged to 1 in 5 steps
#+END_SRC

* collatz_main session from 11
Run collatz_main from 11, 1 for verbose input should lead to a bunch
of lines of output.
#+TESTY: program='./collatz_main -echo'
#+BEGIN_SRC sh
Enter the starting integer:
>> 11
The next value in the Collatz sequence is 34
Show output of steps (0:NO, any other int: yes):
>> 1
Step 0: 11
Step 1: 34
Step 2: 17
Step 3: 52
Step 4: 26
Step 5: 13
Step 6: 40
Step 7: 20
Step 8: 10
Step 9: 5
Step 10: 16
Step 11: 8
Step 12: 4
Step 13: 2
Step 14: 1
The starting value 11 converged to 1 in 14 steps
#+END_SRC

* collatz_main session from 12
Run collatz_main from 11, 7 for verbose input should lead to a bunch
of lines of output.
#+TESTY: program='./collatz_main -echo'
#+BEGIN_SRC sh
Enter the starting integer:
>> 12
The next value in the Collatz sequence is 6
Show output of steps (0:NO, any other int: yes):
>> 7
Step 0: 12
Step 1: 6
Step 2: 3
Step 3: 10
Step 4: 5
Step 5: 16
Step 6: 8
Step 7: 4
Step 8: 2
Step 9: 1
The starting value 12 converged to 1 in 9 steps
#+END_SRC
